spring:

  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/kotlin_mini
    password: ROOT
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10